### ISSUE TITLE
Code for the CanLite

### ISSUE THREAD

**Issue by lukilukeskywalker** [voltlog/CanLite#1]
Hi!!!

Is there any code for the CanLite? I am mostly interested in the part of the CAN bus 

Thanks

**Comment by voltlog** [comment]
Hi,
Currently there is no example code for the CanLite. I am working on that, but due to a busy schedule it will take a while until I can get that task done. In the meantime you can use any generic ESP32 CAN interface example code. There are numerous projects on the web on the topic, [here is for example a project based on Arduino.](https://github.com/skpang/esp32can_demo)
