### ISSUE TITLE
The footprint for voltlog:Inductor_7.5x6.6 is missing.

### ISSUE THREAD

**Issue by michaelhay** [voltlog/CanLite#2]

**Comment by voltlog** [comment]
What you are reporting is not possible, because of this (extracted from kicad User Manual)
"KiCad schematic and board files contain all the schematic symbols and footprints used in the design, so you
can back up or send these files by themselves with no issue"
Link: https://docs.kicad.org/6.0/en/kicad/kicad.pdf
